package com.mirkowu.fastread.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mirkowu.fastread.bean.BookDetailBean;

import com.mirkowu.fastread.db.BookDetailBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDetailBeanDaoConfig;

    private final BookDetailBeanDao bookDetailBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDetailBeanDaoConfig = daoConfigMap.get(BookDetailBeanDao.class).clone();
        bookDetailBeanDaoConfig.initIdentityScope(type);

        bookDetailBeanDao = new BookDetailBeanDao(bookDetailBeanDaoConfig, this);

        registerDao(BookDetailBean.class, bookDetailBeanDao);
    }
    
    public void clear() {
        bookDetailBeanDaoConfig.clearIdentityScope();
    }

    public BookDetailBeanDao getBookDetailBeanDao() {
        return bookDetailBeanDao;
    }

}
